sudo: required
dist: trusty
notifications:
  email: false
language: node_js
node_js:
  - '6'
  - '7'
  - '8'
env:
  - WEBPACK_VERSION=3.0
  - WEBPACK_VERSION=3.1
  - WEBPACK_VERSION=3.2
  - WEBPACK_VERSION=3.3
  - WEBPACK_VERSION=3.4
  - WEBPACK_VERSION=3.5
  - WEBPACK_VERSION=3.6
  - WEBPACK_VERSION=3.7
  - WEBPACK_VERSION=3.8
matrix:
  fast_finish: true
cache:
  yarn: true
before_install:
  - export COLUMNS=100 && stty cols 100
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: travis_retry yarn
before_script:
  - travis_retry yarn add "webpack@$WEBPACK_VERSION"
  - yarn build
script: yarn test
